
export const data = [
  {keywords: ['academic integrity','academic conduct'], title: 'Academic Integrity', url: 'https://academicconduct.umbc.edu/'},
  {keywords: ['colab','interdisciplinary colab'], title: 'Interdisciplinary CoLab', url: 'https://iaac.umbc.edu/'},
  {keywords: ['jobs','internships','job','internship'], title: 'Jobs and Internships - myUMBC', url: 'http://my.umbc.edu/topics/jobs-and-internships/'},
  {keywords: ['job','jobs','working','work','career'], title: 'Work at UMBC', url: 'https://jobs.umbc.edu'},
  {keywords: ['password','change password','change my password'], title: 'How to Change Your Password', url: 'https://wiki.umbc.edu/pages/viewpage.action?pageId=1867939'},
  {keywords: ['career fair','job fair'], title: 'Job Fair Calendar', url: 'http://careers2.umbc.edu/calendar/'},
  {keywords: ['modern languages linguistics and intercultural communication','french','russian','modern languages and linguistics','intercultural communication','german','spanish'], title: 'Modern Languages, Linguistics, and Intercultural Communication', url: 'http://mlli.umbc.edu/'},
  {keywords: ['retriever fitness center'], title: 'Retriever Fitness Center', url: 'http://my.umbc.edu/groups/recsports/'},
  {keywords: ['computer science and electrical engineering','computer engineering','computer science','electrical engineering','engineering management','systems engineering'], title: 'Computer Science and Electrical Engineering', url: 'http://www.csee.umbc.edu/'},
  {keywords: ['rac','the rac','retriever athletic center','the retriever athletic center','gym'], title: 'Retriever Athletic Center', url: 'http://my.umbc.edu/groups/recsports/'},
  {keywords: ['financial aid','scholarship','scholarships','financial and and scholarships','office of financial aid and scholarships','office of financial aid'], title: 'Financial Aid and Scholarships', url: 'http://financialaid.umbc.edu/'},
  {keywords: ['graduation','apply for graduation','commencement','ceremony ceremony','commencement ceremony'], title: 'Graduation Information', url: 'http://registrar.umbc.edu/services/graduation/'},
  {keywords: ['catalog','catalogue','undergraduate catalog','course catalog','course catalogue'], title: 'Undergraduate Catalog', url: 'http://catalog.umbc.edu/'},
  {keywords: ['the retriever weekly','trw','newspaper','campus paper'], title: 'The Retriever Weekly', url: 'http://www.retrieverweekly.com/'},
  {keywords: ['alumni affairs'], title: 'Alumni Affairs', url: 'http://www.umbc.edu/alumni'},
  {keywords: ['education','early childhood education','elementary education','middle science education','secondary education','teaching','stem'], title: 'Education', url: 'http://education.umbc.edu/'},
  {keywords: ['management advisory services','mas'], title: 'Management Advisory Services (MAS)', url: 'http://mas.umbc.edu/'},
  {keywords: ['imc','international media center'], title: 'International Media Center', url: 'http://doit.umbc.edu/itnm/consulting/imc/'},
  {keywords: ['the commons','commons','events and facilities','scheduling','university center'], title: 'The Commons', url: 'http://www.umbc.edu/commons/'},
  {keywords: ['political science','public administration and policy'], title: 'Political Science', url: 'http://poli.umbc.edu/'},
  {keywords: ['calendar','google calendar','gcal'], title: 'Login to Google Calendar', url: 'http://gcal.umbc.edu/'},
  {keywords: ['athletics and physical recreation'], title: 'Athletics and Physical Recreation', url: 'http://www.umbcretrievers.com/'},
  {keywords: ['history'], title: 'History @ Shady Grove', url: 'http://www.umbc.edu/shadygrove/history/'},
  {keywords: ['human centered computing','hcc'], title: 'Human Centered Computing', url: 'http://www.hcc.umbc.edu/'},
  {keywords: ['central receiving'], title: 'Central Receiving', url: 'http://www.umbc.edu/centralreceiving/'},
  {keywords: ['human resources','hr'], title: 'Department of Human Resources', url: 'http://hr.umbc.edu/'},
  {keywords: ['reslife','residential life','res life','residency','residence life','resident life','residence halls'], title: 'Residential Life', url: 'http://www.umbc.edu/reslife/'},
  {keywords: ['r25','room reservation','reserve','reservation'], title: 'R25', url: 'http://umbc.edu/go/r25/'},
  {keywords: ['sustainability','recycling','eco friendly','environment','recycle','recyclemania','recycle mania'], title: 'Sustainability', url: 'http://sustainability.umbc.edu/'},
  {keywords: ['philosophy'], title: 'Philosophy', url: 'http://www.umbc.edu/philosophy/'},
  {keywords: ['cybersecurity','cybersecurity strategy and policy'], title: 'Cybersecurity', url: 'http://www.umbc.edu/cyber/'},
  {keywords: ['gender and womens studies','gwst'], title: 'Gender and Women\'s Studies', url: 'http://gwst.umbc.edu/'},
  {keywords: ['womens center','women\'s center','the womens center'], title: 'Women\'s Center', url: 'http://womenscenter.umbc.edu/'},
  {keywords: ['sociology','anthropology','applied sociology','cultural anthropology'], title: 'Sociology and Anthropology', url: 'http://sociology.umbc.edu/'},
  {keywords: ['visual arts','imaging and digital arts','digital arts'], title: 'Visual Arts', url: 'http://art.umbc.edu/'},
  {keywords: ['industrial organizational psychology'], title: 'Industrial/Organizational Psychology @ Shady Grove', url: 'http://www.umbc.edu/shadygrove/io/'},
  {keywords: ['account','username','user'], title: 'Accounts Help', url: 'https://wiki.umbc.edu/display/faq/Accounts'},
  {keywords: ['seb','student events board'], title: 'Student Events Board (SEB)', url: 'http://seb.umbc.edu/'},
  {keywords: ['student support services','sss'], title: 'Student Support Services', url: 'http://sss.umbc.edu/'},
  {keywords: ['health administration policy','happ','health administration and policy'], title: 'Health Administration and Policy', url: 'http://happ.umbc.edu/'},
  {keywords: ['asian studies'], title: 'Asian Studies', url: 'http://asianstudies.umbc.edu/'},
  {keywords: ['placement test','placement testing','english placement test','math placement test','placement','reading placement test','english placement','reading placement'], title: 'Placement Testing', url: 'http://orientation.umbc.edu/placement-testing/'},
  {keywords: ['psych','psychology','department of psychology','applied developmental psychology','human services psychology','psychology of the workplace'], title: 'Department of Psychology', url: 'http://psychology.umbc.edu/'},
  {keywords: ['transcript','transcripts','official transcript','transcript request','request transcript','request a transcript'], title: 'Requesting a Transcript from UMBC', url: 'http://umbc.edu/go/transcript/'},
  {keywords: ['radio','radio station','wmbc'], title: 'Radio Station (WMBC)', url: 'http://wmbc.umbc.edu/'},
  {keywords: ['advising','advisor','nursing','pre-professional advising'], title: 'Office for Academic and Pre-Professional Advising', url: 'http://advising.umbc.edu/'},
  {keywords: ['music','american contemporary music'], title: 'Music', url: 'http://music.umbc.edu/'},
  {keywords: ['physics','applied physics','atmospheric physics'], title: 'Physics', url: 'http://physics.umbc.edu/'},
  {keywords: ['uhs','health services','health center','university health services','university health center'], title: 'University Health Services', url: 'http://www.umbc.edu/uhs/'},
  {keywords: ['umbcworks','umbc works'], title: 'UMBCworks', url: 'http://careers.umbc.edu/umbcworks/'},
  {keywords: ['human context of science and technology','hcst'], title: 'Human Context of Science and Technology', url: 'http://userpages.umbc.edu/%7Etatarewi/HCST'},
  {keywords: ['gest','goddard earth sciences and technology center'], title: 'Goddard Earth Sciences and Technology Center (GEST)', url: 'http://gest.umbc.edu/'},
  {keywords: ['english language center'], title: 'English Language Center', url: 'http://www.umbc.edu/elc/'},
  {keywords: ['degree audit'], title: 'Registrar\'s Office - Degree Audit', url: 'http://registrar.umbc.edu/services/degree-audit/'},
  {keywords: ['ocr','office of civil rights','ocr investigation','ocr faq'], title: 'FAQ: title IX and OCR', url: 'https://humanrelations.umbc.edu/q-a-title-ix-and-ocr/'},
  {keywords: ['equal employment opportunity eeo','fair practice','civil rights','adverse impact','discrimination','race discrimination','sex discrimination','religious discrimination','pregnancy discrimination','age discrimination','disability discrimination','veteran discrimination','military service discrimination','gender discrimination'], title: 'Non-Discrimination', url: 'https://humanrelations.umbc.edu/non-discrimination/'},
  {keywords: ['equal employment opportunity eeo','fair practice','civil rights','adverse impact','discrimination','race discrimination','sex discrimination','religious discrimination','pregnancy discrimination','age discrimination','disability discrimination','veteran discrimination','military service discrimination','gender discrimination'], title: 'Human Relations', url: 'https://humanrelations.umbc.edu/'},
  {keywords: ['dance'], title: 'Dance', url: 'http://dance.umbc.edu/'},
  {keywords: ['ancient studies','greek','latin'], title: 'Ancient Studies', url: 'http://ancientstudies.umbc.edu/'},
  {keywords: ['sbs','bursar','burser','bursars office','bursars','student business services','billing','bill','account inquiry','tuition','tuition and fees','fees','bursar office'], title: 'Student Business Services', url: 'http://sbs.umbc.edu/'},
  {keywords: ['judaic studies'], title: 'Judaic Studies', url: 'http://judaicstudies.umbc.edu/'},
  {keywords: ['career services center','career development center'], title: 'Career Services Center', url: 'http://careers.umbc.edu/'},
  {keywords: ['employment','employment opportunities'], title: 'Department of Human Resources - Employment', url: 'http://hr.umbc.edu/employment/job-opportunities/'},
  {keywords: ['bwtech','technology center'], title: 'Technology Center', url: 'http://www.bwtechumbc.com/'},
  {keywords: ['political science'], title: 'Political Science @ Shady Grove', url: 'http://www.umbc.edu/shadygrove/politicalscience/'},
  {keywords: ['blackboard','bb'], title: 'Blackboard Help', url: 'https://wiki.umbc.edu/display/faq/Blackboard'},
  {keywords: ['chemistry and biochemistry'], title: 'Chemistry and Biochemistry', url: 'http://chemistry.umbc.edu/'},
  {keywords: ['transit','bus','transportation','shuttle service','shuttle','umbc transit','shuttle bus','bus schedule','bus routes','shuttle schedule'], title: 'UMBC Transit', url: 'http://www.umbc.edu/transit/'},
  {keywords: ['majors','programs','minors','minor','certificate program','certificate'], title: 'Undergraduate Admissions: Learn/Majors', url: 'http://undergraduate.umbc.edu/majors.php'},
  {keywords: ['information systems','auditing for information systems','business technology administration','decision making support','management science','network administration','project management for information systems','web development'], title: 'Information Systems', url: 'http://www.is.umbc.edu/'},
  {keywords: ['faq','help'], title: 'Find Help (FAQ\'s)', url: 'https://wiki.umbc.edu/display/faq'},
  {keywords: ['schedule','schedule of classes','class schedule'], title: 'Schedule of Classes', url: 'http://umbc.edu/go/schedule/'},
  {keywords: ['honors college'], title: 'Honors College', url: 'http://honors.umbc.edu/'},
  {keywords: ['orientation'], title: 'UMBC Undergraduate Orientation', url: 'http://orientation.umbc.edu/'},
  {keywords: ['campus map','campus maps','maps','map','umbc map','map of campus'], title: 'Campus Maps', url: 'http://about.umbc.edu/visitors-guide/campus-map/'},
  {keywords: ['google'], title: 'Google @ UMBC', url: 'https://sites.google.com/a/umbc.edu/gmail-migration/home'},
  {keywords: ['rt','request tracker','rt ticket','ticket'], title: 'Request Tracker (RT) FAQ\'s', url: 'https://wiki.umbc.edu/pages/viewpage.action?pageId=217255'},
  {keywords: ['procurement'], title: 'Procurement', url: 'http://procurement.umbc.edu/'},
  {keywords: ['health form','health forms','screening','health requirement'], title: 'Incoming Students - University Health Services', url: 'http://www.umbc.edu/uhs/incoming/'},
  {keywords: ['social work','school of social work','sowk'], title: 'School of Social Work', url: 'http://socialwork.umbc.edu/'},
  {keywords: ['bookstore','book store','books','textbook','textbooks','text books','text book','gifts','supplies','umbc bookstore','umbc book store'], title: 'UMBC Bookstore', url: 'http://bookstore.umbc.edu'},
  {keywords: ['training centers'], title: 'Training Centers', url: 'http://umbctraining.com/'},
  {keywords: ['catalog','catalogue','graduate catalog','course catalog','course catalogue'], title: 'Graduate School Catalog', url: 'http://catalog.umbc.edu/index.php?catoid=4'},
  {keywords: ['human relations'], title: 'Human Relations', url: 'http://humanrelations.umbc.edu/'},
  {keywords: ['policy','policies'], title: 'UMBC Policies', url: 'http://www.umbc.edu/policies/'},
  {keywords: ['administration and finance'], title: 'Administration and Finance', url: 'http://adminfinance.umbc.edu/'},
  {keywords: ['college of arts humanities and social sciences','cahss'], title: 'College of Arts, Humanities, and Social Sciences', url: 'http://cahss.umbc.edu/'},
  {keywords: ['gerontology'], title: 'Gerontology', url: 'http://www.gerontologyphd.umaryland.edu'},
  {keywords: ['biology','biological sciences','biology department','department of biology','department of biological sciences'], title: 'Department of Biological Sciences', url: 'http://biology.umbc.edu/'},
  {keywords: ['english'], title: 'English', url: 'http://english.umbc.edu/'},
  {keywords: ['chemical biochemical and environmental engineering','chemical and biochemical engineering','chemical engineering'], title: 'Chemical, Biochemical and Environmental Engineering', url: 'http://cbee.umbc.edu/'},
  {keywords: ['social work'], title: 'Social Work @ Shady Grove', url: 'http://www.umbc.edu/shadygrove/socialwork/'},
  {keywords: ['student judicial programs','judicial'], title: 'Student Judicial Programs', url: 'http://www.umbc.edu/sjp/'},
  {keywords: ['physics education'], title: 'Physics Education', url: 'http://www.umbc.edu/catalog/display.php?major=27'},
  {keywords: ['myumbc','my umbc'], title: 'myUMBC', url: 'http://my.umbc.edu/'},
  {keywords: ['esol','tesol'], title: 'ESOL', url: 'http://www.umbc.edu/esol/'},
  {keywords: ['meyerhoff','meyerhoff scholarship program'], title: 'Meyerhoff Scholarship Program', url: 'http://meyerhoff.umbc.edu/'},
  {keywords: ['astronomy'], title: 'Astronomy', url: 'http://www.jca.umbc.edu'},
  {keywords: ['geographic information systems','gis'], title: 'Geographic Information Systems @ Shady Grove', url: 'http://www.umbc.edu/shadygrove/gis/'},
  {keywords: ['parking','parking services','student parking','faculty parking','parking permit','parking permits'], title: 'Parking Services', url: 'http://www.umbc.edu/parking/'},
  {keywords: ['financial services','accounting','budget office','comptrollers office'], title: 'Financial Services', url: 'http://financialservices.umbc.edu/'},
  {keywords: ['dining','umbc dining','meal plan','meal plans','dining services','dining hall','true grits','chartwells','food','catering','food services'], title: 'Dining Services', url: 'http://www.dineoncampus.com/umbc/'},
  {keywords: ['conflict resolution','mediation','conflict coaching','facilitation'], title: 'Conflict Resolution', url: 'https://humanrelations.umbc.edu/conflict-resolution/'},
  {keywords: ['chemistry','chemistry education'], title: 'Chemistry', url: 'http://chemistry.umbc.edu/'},
  {keywords: ['civil engineering'], title: 'Civil Engineering', url: 'http://www.umbc.edu/engineering/cee/'},
  {keywords: ['blackboard','bb','black board'], title: 'Login to Blackboard', url: 'http://blackboard.umbc.edu/'},
  {keywords: ['email'], title: 'Email Help', url: 'https://wiki.umbc.edu/display/faq/Email/'},
  {keywords: ['registrar','registration','register','registrars office'], title: 'Registrar\'s Office', url: 'http://registrar.umbc.edu/'},
  {keywords: ['osp','sponsored programs'], title: 'Office of Sponsored Programs', url: 'http://research.umbc.edu/office-of-sponsored-programs/'},
  {keywords: ['student life','office of student life'], title: 'Office of Student Life', url: 'http://osl.umbc.edu/'},
  {keywords: ['campus card','campus id'], title: 'Campus Card and Mail Services', url: 'http://campuscard.umbc.edu/'},
  {keywords: ['aok','kuhn','albin o. kuhn','albin o kuhn','library','umbc library','aok library','special collections','research','reference','electronic resources','online public access catalog'], title: 'Albin O. Kuhn Library and Gallery', url: 'http://www.umbc.edu/library/'},
  {keywords: ['aging studies'], title: 'Aging Studies', url: 'http://erickson.umbc.edu/'},
  {keywords: ['mechanical engineering','mechatronics','computational thermal fluid dymanics'], title: 'Mechanical Engineering', url: 'http://me.umbc.edu/'},
  {keywords: ['gmail'], title: 'Login to UMBC Gmail', url: 'http://gmail.umbc.edu/'},
  {keywords: ['history','east asian history'], title: 'History', url: 'http://history.umbc.edu'},
  {keywords: ['media and communication studies','mcs'], title: 'Media and Communication Studies', url: 'http://mcs.umbc.edu/'},
  {keywords: ['student affairs'], title: 'Student Affairs', url: 'http://www.umbc.edu/saf/'},
  {keywords: ['institutional research','office of institutional research'], title: 'Office of Institutional Research', url: 'http://oir.umbc.edu/'},
  {keywords: ['language literacy and culture','llc'], title: 'Language Literacy and Culture', url: 'http://llc.umbc.edu/'},
  {keywords: ['pltw','project lead the way'], title: 'Project Lead the Way', url: 'http://pltw.umbc.edu'},
  {keywords: ['gpa calculator','gpa'], title: 'GPA Calculator', url: 'http://umbc.edu/go/3'},
  {keywords: ['graduate school','grad school'], title: 'Graduate School', url: 'http://gradschool.umbc.edu/'},
  {keywords: ['american studies'], title: 'American Studies', url: 'http://amst.umbc.edu/'},
  {keywords: ['geography and environmental systems','ges','cartography','environmental studies','geography','environmental science','geographic information science applications','geographic information systems'], title: 'Geography and Environmental Systems', url: 'http://ges.umbc.edu/'},
  {keywords: ['engineering management'], title: 'Engineering Management', url: 'http://www.umbc.edu/engm/'},
  {keywords: ['google documents','gdocs'], title: 'Login to Google Docs', url: 'http://gdocs.umbc.edu/'},
  {keywords: ['address','campus address','phone number','campus phone','campus phone number','telephone number','mailing address','umbc address','umbc campus address','umbc phone number'], title: 'UMBC Campus Address and Phone Number', url: 'http://about.umbc.edu/visitors-guide/directions/'},
  {keywords: ['webmail'], title: 'Login to UMBC Webmail', url: 'http://webmail.umbc.edu'},
  {keywords: ['preprofessional and allied health'], title: 'Preprofessional and Allied Health', url: 'http://www.umbc.edu/catalog/display.php?major=32'},
  {keywords: ['college of engineering and information technology','coeit'], title: 'College of Engineering and Information Technology', url: 'http://coeit.umbc.edu/'},
  {keywords: ['religious studies'], title: 'Religious Studies', url: 'http://www.umbc.edu/undergraduate/majors/rel.html'},
  {keywords: ['biochemistry'], title: 'Biochemistry', url: 'http://chemistry.umbc.edu/'},
  {keywords: ['continuing and professional studies','division of professional studies'], title: 'Division of Professional Studies', url: 'http://www.umbc.edu/dps/'},
  {keywords: ['calendar','calender','google calendar','gcal'], title: 'Google Calendar Help', url: 'https://wiki.umbc.edu/display/faq/Google+Calendar'},
  {keywords: ['biochemical regulatory engineering'], title: 'Biochemical Regulatory Engineering', url: 'http://www.umbc.edu/engineering/bre.html'},
  {keywords: ['oit','doit','information technology','division of information technology','helpdesk','audio visual services','av services','help desk'], title: 'Division of Information Technology', url: 'https://doit.umbc.edu/'},
  {keywords: ['provost','office of the provost','provosts office'], title: 'Provost\'s Office', url: 'https://provost.umbc.edu/'},
  {keywords: ['psychology'], title: 'Psychology @ Shady Grove', url: 'http://www.umbc.edu/shadygrove/psychology/'},
  {keywords: ['academic calendar','academic calender','academic dates and deadlines','academic dates','registration dates','registration deadlines','calendar'], title: 'Registrar\'s Office - Academic Calendar', url: 'https://registrar.umbc.edu/calendars/academic-calendars/'},
  {keywords: ['emergency','police','escort service'], title: 'Police', url: 'https://police.umbc.edu/'},
  {keywords: ['shriver center','shriver','the shriver center'], title: 'The Shriver Center', url: 'https://shrivercenter.umbc.edu/'},
  {keywords: ['ehs','department of emergency health services','emergency health services'], title: 'Department of Emergency Health Services', url: 'https://ehs.umbc.edu'},
  {keywords: ['biotechnology','biotechnology management'], title: 'Biotechnology', url: 'http://www.umbc.edu/biotech/'},
  {keywords: ['distance education','instructional systems development','instructional technology'], title: 'Distance Education, Instructional Systems Development and Instructional Technology', url: 'http://isd.umbc.edu/'},
  {keywords: ['marine-estuarine environmental science','mees'], title: 'Marine-Estuarine Environmental Science', url: 'https://gradschool.umbc.edu/admissions/programs/mees/'},
  {keywords: ['mathematics and statistics','math','statistics','stat','applied mathematics','mathematics'], title: 'Mathematics and Statistics', url: 'https://mathstat.umbc.edu/'},
  {keywords: ['theatre','acting'], title: 'Theatre', url: 'https://theatre.umbc.edu/'},
  {keywords: ['africana studies'], title: 'Africana Studies', url: 'https://africanastudies.umbc.edu/'},
  {keywords: ['freeman','hrabowski','freeman hrabowski','president','umbc president','dr hrabowski','dr. hrabowski','presidents office'], title: 'UMBC President, Dr. Freeman A. Hrabowski, III', url: 'https://president.umbc.edu/'},
  {keywords: ['graduate public policy','masters in public policy','doctorate in public policy','public administration','health policy','urban policy','public management','education policy','state government','federal government','local government','public policy schools','public policy jobs','public policy degree','policy analysis','public policy intern'], title: 'Department of Public Policy', url: 'https://publicpolicy.umbc.edu/'},
  {keywords: ['biological sciences','biochemistry and molecular biology','bioinformatics and computational biology','molecular and cell biology','applied molecular biology','neurosciences and cognitive sciences'], title: 'Biological Sciences', url: 'https://biology.umbc.edu/'},
  {keywords: ['facilities management','work control'], title: 'Facilities Management', url: 'https://fm.umbc.edu/'},
  {keywords: ['interdisciplinary studies','inds'], title: 'Interdisciplinary Studies', url: 'https://inds.umbc.edu/'},
  {keywords: ['economics','accounting','economic policy analysis','finance','financial economics'], title: 'Economics', url: 'https://economics.umbc.edu/'},
  {keywords: ['visual and performing arts','vpa'], title: 'Visual and Performing Arts', url: 'http://www.umbc.edu/vpadept/'}];
  
  